FROM postgres:16

# Install OpenSSL and sudo
RUN apt-get update && apt-get install -y openssl sudo build-essential libpq-dev git postgresql-server-dev-16

# Clone and install pg_hashids
RUN git clone https://github.com/iCyberon/pg_hashids /tmp/pg_hashids
WORKDIR /tmp/pg_hashids
RUN PATH=/var/lib/postgresql/16/bin:$PATH USE_PGXS=1 make && USE_PGXS=1 make install

# Allow the postgres user to execute certain commands as root without a password
RUN echo "postgres ALL=(root) NOPASSWD: /usr/bin/mkdir, /bin/chown, /usr/bin/openssl" > /etc/sudoers.d/postgres

# Add init scripts while setting permissions
COPY --chmod=755 init-ssl.sh /docker-entrypoint-initdb.d/init-ssl.sh
COPY --chmod=755 wrapper.sh /usr/local/bin/wrapper.sh

ENTRYPOINT ["wrapper.sh"]
CMD ["postgres", "--port=5432"]
